### ISSUE TITLE
Sample code to write EXIF data in JPEG

### ISSUE THREAD

**Issue by leslie-qiwa** [dsoprea/go-jpeg-image-structure#1]
Seems like it has codes to read EXIF data from JPEG, but not for writing EXIF data into JPEG. Can you please add some codes for that? thanks

**Comment by dsoprea** [comment]
Look for the Exif() and SetExif() methods.

They're both together: https://github.com/dsoprea/go-jpeg-image-structure/blob/master/jpeg.go#L184
