### ISSUE TITLE
runtime error: slice bounds out of range when parsing valid jpeg file

### ISSUE THREAD

**Issue by lastzero** [dsoprea/go-jpeg-image-structure#10]
When trying to parse [this JPEG file](https://raw.githubusercontent.com/photoprism/photoprism/develop/internal/meta/testdata/image-2011.jpg), the error "runtime error: slice bounds out of range [:9955] with capacity 4935" is returned. This is a smaller version of the file attached to https://github.com/photoprism/photoprism/issues/304, created it with Photoshop 2020. So it should be somewhat valid.

Added a fallback so that `exif.SearchFileAndExtractExif` is used in case it fails: https://github.com/photoprism/photoprism/blob/develop/internal/meta/exif.go#L63

The original issue I tried to fix is the missing / wrong date. Works now when using DateTime instead of DateTimeOriginal with the original file (not resized with Photoshop). Resized version still has the wrong date, probably since DateTime holds the modification date, not the original date:
https://github.com/photoprism/photoprism/blob/develop/internal/meta/exif_test.go#L153

**Comment by dsoprea** [comment]
Fixed. We were improperly identifying thumbnails by seeing the tags that had the same ID but were in the wrong IFDs, and trying to get the thumbnail bytes using the offset stored as the value, when that is just a simple scalar for the other tag (the one that happens to have the same ID) and _not_ an offset.

Technically it's fixed, but a) the Go index still hasn't updated to reflect the newer revision of go-exif for the go-jpeg-image-stucture go.mod, and b) I'd like to investigate a broken test before you take-up the new version.

```
go-jpeg-image-structure]$ go run command/js_exif/main.go -f image-2011.jpg
 0: IFD-PATH=[IFD] ID=(0x100) NAME=[ImageWidth] TYPE=(3):[SHORT] VALUE=[[2560]]
 1: IFD-PATH=[IFD] ID=(0x101) NAME=[ImageLength] TYPE=(3):[SHORT] VALUE=[[1920]]
 2: IFD-PATH=[IFD] ID=(0x102) NAME=[BitsPerSample] TYPE=(3):[SHORT] VALUE=[[8 8 8]]
 3: IFD-PATH=[IFD] ID=(0x106) NAME=[PhotometricInterpretation] TYPE=(3):[SHORT] VALUE=[[2]]
 4: IFD-PATH=[IFD] ID=(0x10f) NAME=[Make] TYPE=(2):[ASCII] VALUE=[SAMSUNG            ]
 5: IFD-PATH=[IFD] ID=(0x110) NAME=[Model] TYPE=(2):[ASCII] VALUE=[GT-I9000]
 6: IFD-PATH=[IFD] ID=(0x112) NAME=[Orientation] TYPE=(3):[SHORT] VALUE=[[1]]
 7: IFD-PATH=[IFD] ID=(0x115) NAME=[SamplesPerPixel] TYPE=(3):[SHORT] VALUE=[[3]]
 8: IFD-PATH=[IFD] ID=(0x11a) NAME=[XResolution] TYPE=(5):[RATIONAL] VALUE=[[{720000 10000}]]
 9: IFD-PATH=[IFD] ID=(0x11b) NAME=[YResolution] TYPE=(5):[RATIONAL] VALUE=[[{720000 10000}]]
10: IFD-PATH=[IFD] ID=(0x128) NAME=[ResolutionUnit] TYPE=(3):[SHORT] VALUE=[[2]]
11: IFD-PATH=[IFD] ID=(0x131) NAME=[Software] TYPE=(2):[ASCII] VALUE=[Adobe Photoshop 21.1 (Macintosh)]
12: IFD-PATH=[IFD] ID=(0x132) NAME=[DateTime] TYPE=(2):[ASCII] VALUE=[2020:05:15 10:25:45]
13: IFD-PATH=[IFD] ID=(0x829a) NAME=[ExposureTime] TYPE=(10):[SRATIONAL] VALUE=[[{9 10000}]]
14: IFD-PATH=[IFD] ID=(0x829d) NAME=[FNumber] TYPE=(10):[SRATIONAL] VALUE=[[{263899999 100000000}]]
...
```

**Comment by lastzero** [comment]
Amazing, thank you! :)

**Comment by dsoprea** [comment]
That one was buried. It took me hours.

**Comment by dsoprea** [comment]
Okay. The unit-test issue has been resolved. Feel free to use latest.

https://github.com/dsoprea/go-exif/commit/efa6e2d6c081c7f79732038c84cb1f8f4cd1c0b4
