### ISSUE TITLE
LooksLikeFormat fails incorrectly

### ISSUE THREAD

**Issue by neurosnap** [dsoprea/go-jpeg-image-structure#18]
I have a jpg image that fails the `LooksLikeFormat` test.

In particular is fails on this check `data[l-2] != 0xff`  I'd be happy to share the image to help debug.

The image was captured with a FUJIFILM FI019

**Comment by dsoprea** [comment]
Yes. Please share a link to it (lest embedding it make it an untrue
representation) or even a PR if you're compelled.

**Comment by neurosnap** [comment]
https://ben.imgs.sh/o/kinopio-3d
