### ISSUE TITLE
Ending-on-EOI strictness

### ISSUE THREAD

**Issue by dsoprea** [dsoprea/go-jpeg-image-structure#6]
When observing some nonconformancy, we added some strictness in order to be able to more-effectively debug. However, this unexpectedly broke @lastzero.

https://github.com/dsoprea/go-jpeg-image-structure/commit/735e765a68ee505277be112de8f4eb4a25ed9870#r38329551

We're reverting for now and will revisit in the [dustin/add_eoi_strictness](https://github.com/dsoprea/go-jpeg-image-structure/tree/dustin/add_eoi_strictness) branch.

**Comment by dsoprea** [comment]
Disregarding this effort. We've refactored how we detect EOI. 0e92dc521844ff3bc00f3cbb56b20749e3fac974

**Comment by lastzero** [comment]
Very nice, so upgrading is a good idea?

**Comment by dsoprea** [comment]
Yeah. I also added a similar strictness assertion as last time, but the fix should tame it to only cause a problem for JPEG that have a bunch if junk on the end, which violates the spec (a JPEG must have an EOI after the SOS/scan-data, the file must end on an EOI, and there can be only one EOI). I wanted some minimum strictness to help with debugging and if it causes some huge problem with some subpopulation of users, I need to know sooner than later. Plus, that'll also give me the opportunity to just account for that variation.

**Comment by lastzero** [comment]
Seems to work very well so far. Thank you! :)

**Comment by dsoprea** [comment]
Thanks for keeping an eye out.
