### ISSUE TITLE
rename repository to same name as package?

### ISSUE THREAD

**Issue by rcoreilly** [dsoprea/go-jpeg-image-structure#9]
First, thanks a ton for this and the go-exif packages -- working great overall for a go-based photo management app I'm writing.

Just a quick question as to why you don't rename the repository to the same name as the package (jpegstructure), which is go standard practice?  I haven't used any other packages actually that have had that discrepancy so far..  same goes for go-exif which could be renamed simply exif per its package name.

**Comment by dsoprea** [comment]
The convention is for the package name to be concise whereas the project name can be descriptive.

It's a moot point. These projects are released and adopted and won't be changed.
